"""Regenerate tests/fixtures/geodesy_cases.json from the Python implementation.

The fixture is the contract between ``pipeline/common/geodesy.py`` and the
JavaScript copy in ``src/viewer-2d/netcdf.js``. Python is the reference side, so
the expected values are generated from it and the JavaScript is asserted against
them -- not the other way round, and never both regenerated from themselves,
which would agree with whatever they currently do.

Run it only when the contract itself changes, and re-run both suites afterwards:

    python -m tests.regenerate_geodesy_fixture
    python -m unittest discover -s tests -t .
    node --test "tests/*.test.mjs"

A diff to this fixture in a review means a rule changed. That is the point.
"""

from __future__ import annotations

import json
from pathlib import Path

from pipeline.common.geodesy import (
    geotransform_error,
    is_north_up,
    mercator_to_lonlat,
    parse_geotransform,
)

#: Origin, both hemispheres, the pilot unit's own corner, the plane's edge where
#: the atan/exp form is least well behaved, and a sub-metre value.
MERCATOR_POINTS = [
    ("origin", 0.0, 0.0),
    ("pilot-nw", -10832000.0, 3530000.0),
    ("southern", 4000000.0, -2500000.0),
    ("plane-edge", 20037508.342789244, 20037508.342789244),
    ("sub-metre", 1.0, 1.0),
]

#: (name, text, should parse). The rejections matter more than the acceptances:
#: each one is a way a file has been, or could be, unpublishable.
GEOTRANSFORMS = [
    ("north-up", "100 2 0 500 0 -2", True),
    ("negative-origin", "-10832000.5 3.0 0 3530000.25 0 -3.0", True),
    ("rotated", "0 1 0.5 0 -0.25 -1", True),
    ("extra-whitespace", "  0   1 0   0 0  -1  ", True),
    ("five-numbers", "0 1 0 0 0", False),
    ("seven-numbers", "0 1 0 0 0 -1 9", False),
    ("non-numeric", "0 1 0 0 0 south", False),
    ("nan", "0 1 0 0 0 NaN", False),
    ("infinite", "0 1 0 Infinity 0 -1", False),
    ("empty", "", False),
]

COMMENT = [
    "Shared by tests/test_geodesy.py and tests/netcdf-reader.test.mjs.",
    "pipeline/common/geodesy.py and src/viewer-2d/netcdf.js implement the",
    "same rules in two languages because the browser cannot import Python.",
    "Both are asserted against these values, so a change to one that is not",
    "made to the other fails rather than drifting silently.",
    "Field names differ by language on purpose: Python returns snake_case",
    "keys, JavaScript returns camelCase. 'parsed' uses the Python names and",
    "the JS test maps them.",
    "Generated by tests/regenerate_geodesy_fixture.py -- do not hand-edit.",
]

#: 1e-9 degrees is about 0.1 mm. The two implementations use the same formula
#: written differently, so they agree to well within this.
TOLERANCE_DEG = 1e-9


def build() -> dict:
    mercator = []
    for name, x, y in MERCATOR_POINTS:
        lon, lat = mercator_to_lonlat(x, y)
        mercator.append({"name": name, "x": x, "y": y, "lon": lon, "lat": lat})

    geotransform = []
    for name, text, should_parse in GEOTRANSFORMS:
        gt = parse_geotransform(text)
        if (gt is not None) != should_parse:
            raise SystemExit(
                f"{name!r}: parse_geotransform returned {gt!r}, expected "
                f"{'a transform' if should_parse else 'None'}. Either the case "
                f"is wrong or geodesy.py changed; decide which before regenerating."
            )
        entry = {"name": name, "text": text, "valid": gt is not None,
                 "error": geotransform_error(text)}
        if gt is not None:
            entry["parsed"] = gt
            entry["north_up"] = is_north_up(gt)
        geotransform.append(entry)

    return {
        "_comment": COMMENT,
        "mercator_tolerance_deg": TOLERANCE_DEG,
        "mercator": mercator,
        "geotransform": geotransform,
    }


def main() -> int:
    target = Path(__file__).resolve().parent / "fixtures" / "geodesy_cases.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(build(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {target}")
    print(f"  {len(MERCATOR_POINTS)} mercator points, {len(GEOTRANSFORMS)} geotransforms")
    print("  now run both suites; a JavaScript failure means netcdf.js needs the same change")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
