/* Generated by pipeline/fim1d/site.py -- do not edit by hand.

   Per-deployment settings for a published release.

   Every profile in this release was baked into a static PMTiles archive,
   so there is no tile service to point at and this stays null. */
window.FIMCFG = {
  manifest: "manifest.json",
  rasterTileBase: null,
  initialCenter: [-97.22782, 30.09025],
  initialZoom: 9.5
};
